### ISSUE TITLE
design bug with footer hight

### ISSUE THREAD

**Issue by SimonKoehl** [serlo/athene2#869]
I added an additional footer item. That led to white space below "Spenden/Mitmachen" at the right bottom: https://de.serlo.org/partner

**Comment by elbotho** [comment]
won't be a problem in the new layout, 
can be fixed with increasing the min-height on `#mission-statement-claim`:

``` css
@media (min-width: 1240px)
#footer #mission-statement #mission-statement-claim {
    padding: 62px 50px 28px;
    min-height: 320px;
}
```
